# .github/workflows/test.yml
name: Run Scheduled Unit Tests

on:
  schedule:
    - cron: '0 5 * * *' # everyday at 5:00 UTC
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run unit tests
        run: npm test
